# Aufruf:   docker compose up

services:
  trivy:
    image: owasp/dependency-check:8.4.0
    command:
      - '--scan'
      - '/dependency-check/src'
      - '--format'
      - 'ALL'
      - '--project'
      - 'buch'
      - '--out'
      - '/dependency-check/report'
      - '--suppression'
      - '/dependency-check/suppression.xml'
    volumes:
      - type: bind
        source: ../../..
        target: /dependency-check/src
      - type: bind
        source: C:/Zimmermann/dependency-check-data
        target: /usr/share/dependency-check/data
      - type: bind
        source: ../../doc/dependency-check
        target: /dependency-check/report
      - type: bind
        source: ./suppression.xml
        target: /dependency-check/suppression.xml
    container_name: dependency-check
    cap_drop: [ALL]
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '2.0'
          memory: 4G
