services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.3-0
    #depends_on: [postgres]
    ports:
      - published: 8080
        target: 8080
    volumes:
      - type: bind
        source: C:/Zimmermann/volumes/keycloak
        # mit Unterverzeichnis h2
        target: /opt/keycloak/data
      # ggf. /opt/keycloak/conf/keycloak.conf
    env_file: keycloak.env
    hostname: keycloak
    container_name: keycloak
    user: keycloak:1000
    # --features=token-exchange
    entrypoint: ['/opt/keycloak/bin/kc.sh', 'start-dev']
    cap_drop: [ALL]
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '2.0'
          memory: 2G
