# https://github.com/prettier/prettier/issues/4102
# https://github.com/prettier/prettier/pull/7466
singleQuote: true
tabWidth: 2
trailingComma: all
overrides:
  - files: ['*.ts', '*.mts', '*.js', '*.mjs', '*.cjs']
    options:
      tabWidth: 4
