# Aufruf:   docker compose [-f compose.yml -f compose.bookworm.yml|compose.wolfi.yml] up

services:
  trivy:
    image: aquasec/trivy:0.45.1
    command: [image, gruppe4/album:2023.10.0-distroless]
    volumes:
      - type: bind
        source: C:/Zimmermann/volumes/trivy
        target: /root/.cache
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    container_name: trivy
    cap_drop: [ALL]
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '2.0'
          memory: 2G
