services:
  fakesmtp:
    image: gessnerfl/fake-smtp-server:2.1.2
    ports:
      - published: 5025
        target: 8025
      - published: 5080
        target: 8080
      - published: 5081
        target: 8081
    volumes:
      - type: bind
        source: C:/Zimmermann/volumes/fakesmtp
        target: /tmp
    environment:
      TZ: Europe/Berlin
      SPRING_OUTPUT_ANSI_ENABLED: ALWAYS
      SPRING_MAIN_BANNER-MODE: LOG
      SPRING_LAZY-INITIALIZATION: true
      SPRING_JPA_OPEN-IN-VIEW: true
    hostname: fakesmtp
    container_name: fakesmtp
    cap_drop: [ALL]
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 768M
        reservations:
          cpus: '0.5'
          memory: 768M
